// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BorderFormItem: typeof import('./src/components/BorderFormItem.vue')['default']
    CommonFormItem: typeof import('./src/components/CommonFormItem.vue')['default']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    Seal: typeof import('./src/components/Seal.vue')['default']
  }
}
